<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{4b0696f6-af6c-46f9-8f33-29d4909b2e53}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	nCounter : INT;
	sText_PC1 : STRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nCounter := nCounter +1;
sText_PC1 := CONCAT('Value = ', TO_STRING(nCounter));]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>